**Task 1:Import Libraries**

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

**Task 2:Load Dataset**

In [6]:
df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

**Task 3:Check Dataset**

In [7]:
print(df.shape)
print(df.columns)
df.info()

(1000, 8)
Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

**Task 4:Convert Text Columns to Numbers**

In [8]:
le = LabelEncoder()

df['gender'] = le.fit_transform(df['gender'])
df['race/ethnicity'] = le.fit_transform(df['race/ethnicity'])
df['parental level of education'] = le.fit_transform(df['parental level of education'])
df['lunch'] = le.fit_transform(df['lunch'])
df['test preparation course'] = le.fit_transform(df['test preparation course'])

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,1,1,1,1,72,72,74
1,0,2,4,1,0,69,90,88
2,0,1,3,1,1,90,95,93
3,1,0,0,0,1,47,57,44
4,1,2,4,1,1,76,78,75

**Tak 5:Select Input and Output**

In [9]:
X = df.drop('math score', axis=1)
y = df['math score']

print("Input Features:")
print(X.head())

print("\nTarget Variable:")
print(y.head())

Input Features:
   gender  race/ethnicity  parental level of education  lunch  \
0       0               1                            1      1
1       0               2                            4      1
2       0               1                            3      1
3       1               0                            0      0
4       1               2                            4      1

   test preparation course  reading score  writing score
0                        1             72             74
1                        0             90             88
2                        1             95             93
3                        1             57             44
4                        1             78             75

Target Variable:
0    72
1    69
2    90
3    47
4    76
Name: math score, dtype: int64

**Task 6:Split Dataset**

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (800, 7)
Testing Data: (200, 7)

**Task 7:Train Machine Learning Model**

In [11]:
model = RandomForestRegressor(random_state=42)

model.fit(X_train, y_train)

print("Model Training Completed")

Model Training Completed

**Task 8:Predict Results**

In [12]:
y_pred = model.predict(X_test)

print("Prediction Completed")

Prediction Completed

**Task 9:Check Accuracy**

In [13]:
accuracy = r2_score(y_test, y_pred)

print("R2 Score:", accuracy)

R2 Score: 0.8487940184356789

**Task 10:Display Actual vs Predicted Score**

In [14]:
result = pd.DataFrame({
    "Actual Score": y_test.values,
    "Predicted Score": y_pred
})

result.head(10)

   Actual Score  Predicted Score
0            91            77.76
1            53            54.74
2            80            76.16
3            74            77.11
4            84            80.96
5            81            85.79
6            69            65.46
7            54            54.42
8            87            73.70
9            51            53.03